sibbay-ai/operating

- mri/menstrual.md
for https://github.com/sibbay-ai/cooperation-issues/issues/679
> 经期管理互动文案设计

- mri/menstrual.md
for https://github.com/sibbay-ai/cooperation-issues/issues/708
@fushang318
> for https://github.com/sibbay-ai/cooperation-issues/issues/708

- 经期互动状态迁移文案.md
> 经期互动状态迁移文案

- ui_design/movie1/视频症状-1.4版本
for https://github.com/sibbay-ai/operating/issues/147
> for#147,症状视频-1.4版本

- ui_design/movie1/视频症状-1.4版本
- ui_design/movie2.0/症状视频-1.5版本
- ui_design/movie2.0/症状视频-5.0版本
for https://github.com/sibbay-ai/operating/issues/148
> for#148，症状视频-1.5版本

- 微信公众号圣诞节海报
> 微信公众号圣诞节海报

- 小白健康-2019年1月每日提示语
> 小白健康-2019年1月每日提示语

- 2019年1月份每日提示语
> 2019年1月份每日提示语

- 春节牵金猪活动海报设计及软文发布及相关工作
>  春节牵金猪活动海报设计及软文发布及相关工作

- 1月微信公众软文撰写及相关工作
> 1月微信公众软文撰写及相关工作

- 春节牵金猪活动海报设计及软文发布相关
> 春节牵金猪活动海报设计及软文发布相关

- 2-3月每日互动首语
> 2-3月每日互动首语

- 小白健康用户群维护及文案相关
>  小白健康用户群维护及文案相关

- 小白健康微信公众号软文编辑发布及相关工作
>  小白健康微信公众号软文编辑发布及相关工作

- 小白健康贡献者3月线下小聚
> 小白健康贡献者3月线下小聚

- 4-5月每日问候海报-小单张
>  4-5月每日问候海报-小单张

- 4-5月每日互动首语
> 4-5月每日互动首语

- 众合社区（52-55期）月报汇集及发布
>  众合社区（52-55期）月报汇集及发布

- 小白健康群维护及每日问候海报
>  小白健康群维护及每日问候海报

- 小白健康6-7月每日互动首语
> 小白健康6-7月每日互动首语

- 小白健康7月上海线下小聚
> 小白健康贡献者7月上海线下小聚

- 小白健康8-9月每日提示语
> 小白健康8-9月每日提示语

- 2019年8-9月小白健康群管理及每日问候海报
>  2019年8-9月小白健康群管理及每日问候海报

- 医学指标录入协助和管理工作
> 医学指标录入协助和管理工作

- 【据小白统计】上线海报发起及协助发布等相关
> 【据小白统计】上线海报发起及协助发布等相关

- 2019年10-11月小白健康每日互动首语
>  2019年10-11月小白健康每日互动首语
